### ISSUE TITLE
Dezoomify won't work on Sotheby's images 

### ISSUE THREAD

**Issue by chengischan** [lovasoa/dezoomify-extension#29] opened 2021-07-31 15:36 UTC
been trying to get it to work on the Sotheby's website. It won't recognize the presence of a zoomable tiled image at all. 

sample url: https://www.sothebys.com/en/buy/auction/2021/modern-contemporary-south-asian-art/savitri-and-yama

image url: https://sothebys-md.brightspotcdn.com/dims4/default/4313cb0/2147483647/strip/true/crop/1247x2000+0+0/resize/800x1283!/quality/90/?url=http%3A%2F%2Fsothebys-brightspot.s3.amazonaws.com%2Fmedia-desk%2F7f%2F64%2F59d75c844269a9953b0bd64f1f21%2F085n10645-bmph2-01.jpg

**Comment by lovasoa** [comment] 2021-08-02 08:50
Duplicate of #509

**Closed by lovasoa** 2021-08-02 08:50 UTC

**Comment by lovasoa** [comment] 2021-08-02 08:52
This is not a This is not a tiled image, you don't need dezoomify, you can download it directly from your browser

https://sothebys-md.brightspotcdn.com/7f/64/59d75c844269a9953b0bd64f1f21/085n10645-bmph2-01.jpg

**Comment by chengischan** [comment] 2021-08-02 10:01
ah! thanks so much
