### ISSUE TITLE
Error 429 Too Many Requests when trying dezoomify on The Peasant Wedding, Google Arts & Culture

### ISSUE THREAD

**Issue by stefanaaltenibm** [lovasoa/dezoomify-extension#6] opened 2020-05-21 17:18 UTC
Hi,

I have installed the dezoomify add-on (v0.4.2) in Firefox (v76.0.1).

I am trying to use dezoomify with Google Arts & Culture to download the hi-res version of The Peasant Wedding by Pieter Bruegel at https://artsandculture.google.com/asset/peasant-wedding/hgGvote2WI8P3w?hl=en-GB&ms=%7B%22x%22%3A0.5%2C%22y%22%3A0.5%2C%22B%22%3A9.523707976632611%2C%22z%22%3A9.523707976632611%2C%22size%22%3A%7B%22width%22%3A1.843923339843752%2C%22height%22%3A1.4031991525423744%7D%7D.

I receive this error: "Error: Unable to fetch https://artsandculture.google.com/asset/peasant-wedding/hgGvote2WI8P3w
The server responded: fopen(https://artsandculture.google.com/asset/peasant-wedding/hgGvote2WI8P3w): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests
(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:405)"

Can you please help?

Many thanks.

Stefan

**Comment by lovasoa** [comment] 2020-05-21 18:27
Hello!
 This issue is a duplicate of https://github.com/lovasoa/dezoomify/issues/337

**Closed** 2020-05-21 18:27 UTC
Labels: duplicate
